import {
  arbitrum,
  arbitrumSepolia,
  base,
  baseSepolia,
  ink,
  linea,
  mainnet,
  mode,
  optimism,
  optimismSepolia,
  scroll,
  sepolia,
  soneium,
  unichain,
  worldchain,
} from "viem/chains";

import {
  arbitrumCapabilities,
  emergingL2Infrastructure,
  ethereumMainnetCapabilities,
  ethereumTestnetCapabilities,
  matureL1Infrastructure,
  matureL2Infrastructure,
  opStackCapabilities,
} from "./presets.js";
import { identityFromViem } from "./from-viem.js";
import type { ChainDefinition } from "./types.js";

export const CHAINS: readonly ChainDefinition[] = [
  {
    key: "ethereum",
    shortName: "ETH",
    networkKind: "mainnet",
    family: "ethereum",
    roles: ["source"],
    capabilities: ethereumMainnetCapabilities,
    infrastructure: matureL1Infrastructure,
    ...identityFromViem(mainnet),
    name: "Ethereum",
  },
  {
    key: "sepolia",
    shortName: "SEP",
    networkKind: "testnet",
    family: "ethereum",
    roles: ["source", "target"],
    testnetOf: "ethereum",
    capabilities: ethereumTestnetCapabilities,
    infrastructure: matureL1Infrastructure,
    ...identityFromViem(sepolia),
    name: "Ethereum Sepolia",
  },
  {
    key: "base",
    shortName: "BASE",
    networkKind: "mainnet",
    family: "op-stack",
    roles: ["source", "target"],
    parentChainKey: "ethereum",
    capabilities: opStackCapabilities,
    infrastructure: matureL2Infrastructure,
    ...identityFromViem(base),
    name: "Base",
  },
  {
    key: "base-sepolia",
    shortName: "BASE-SEP",
    networkKind: "testnet",
    family: "op-stack",
    roles: ["source", "target"],
    parentChainKey: "sepolia",
    testnetOf: "base",
    capabilities: opStackCapabilities,
    infrastructure: matureL2Infrastructure,
    ...identityFromViem(baseSepolia),
    name: "Base Sepolia",
  },
  {
    key: "optimism",
    shortName: "OP",
    networkKind: "mainnet",
    family: "op-stack",
    roles: ["source", "target"],
    parentChainKey: "ethereum",
    capabilities: opStackCapabilities,
    infrastructure: matureL2Infrastructure,
    ...identityFromViem(optimism),
    name: "OP Mainnet",
  },
  {
    key: "optimism-sepolia",
    shortName: "OP-SEP",
    networkKind: "testnet",
    family: "op-stack",
    roles: ["source", "target"],
    parentChainKey: "sepolia",
    testnetOf: "optimism",
    capabilities: opStackCapabilities,
    infrastructure: matureL2Infrastructure,
    ...identityFromViem(optimismSepolia),
    name: "OP Sepolia",
  },
  {
    key: "arbitrum-one",
    shortName: "ARB",
    networkKind: "mainnet",
    family: "arbitrum-orbit",
    roles: ["source", "target"],
    parentChainKey: "ethereum",
    capabilities: arbitrumCapabilities,
    infrastructure: matureL2Infrastructure,
    ...identityFromViem(arbitrum),
    name: "Arbitrum One",
  },
  {
    key: "arbitrum-sepolia",
    shortName: "ARB-SEP",
    networkKind: "testnet",
    family: "arbitrum-orbit",
    roles: ["source", "target"],
    parentChainKey: "sepolia",
    testnetOf: "arbitrum-one",
    capabilities: arbitrumCapabilities,
    infrastructure: matureL2Infrastructure,
    ...identityFromViem(arbitrumSepolia),
    name: "Arbitrum Sepolia",
  },
  {
    key: "scroll",
    shortName: "SCR",
    networkKind: "mainnet",
    family: "other",
    roles: ["target"],
    parentChainKey: "ethereum",
    capabilities: opStackCapabilities,
    infrastructure: emergingL2Infrastructure,
    ...identityFromViem(scroll),
    name: "Scroll",
  },
  {
    key: "linea",
    shortName: "LINEA",
    networkKind: "mainnet",
    family: "other",
    roles: ["target"],
    parentChainKey: "ethereum",
    capabilities: opStackCapabilities,
    infrastructure: emergingL2Infrastructure,
    ...identityFromViem(linea),
    name: "Linea",
  },
  {
    key: "unichain",
    shortName: "UNI",
    networkKind: "mainnet",
    family: "op-stack",
    roles: ["target"],
    parentChainKey: "ethereum",
    capabilities: opStackCapabilities,
    infrastructure: emergingL2Infrastructure,
    ...identityFromViem(unichain),
    name: "Unichain",
  },
  {
    key: "world-chain",
    shortName: "WORLD",
    networkKind: "mainnet",
    family: "op-stack",
    roles: ["target"],
    parentChainKey: "ethereum",
    capabilities: opStackCapabilities,
    infrastructure: emergingL2Infrastructure,
    ...identityFromViem(worldchain),
    name: "World Chain",
  },
  {
    key: "ink",
    shortName: "INK",
    networkKind: "mainnet",
    family: "op-stack",
    roles: ["target"],
    parentChainKey: "ethereum",
    capabilities: opStackCapabilities,
    infrastructure: emergingL2Infrastructure,
    ...identityFromViem(ink),
    name: "Ink",
  },
  {
    key: "soneium",
    shortName: "SONEIUM",
    networkKind: "mainnet",
    family: "op-stack",
    roles: ["target"],
    parentChainKey: "ethereum",
    capabilities: opStackCapabilities,
    infrastructure: emergingL2Infrastructure,
    ...identityFromViem(soneium),
    name: "Soneium",
  },
  {
    key: "mode",
    shortName: "MODE",
    networkKind: "mainnet",
    family: "op-stack",
    roles: ["target"],
    parentChainKey: "ethereum",
    capabilities: opStackCapabilities,
    infrastructure: emergingL2Infrastructure,
    ...identityFromViem(mode),
    name: "Mode",
  },
];
