export const DEPLOYMENT_ERROR_CODES = [
  "INVALID_REQUEST",
  "REVISION_NOT_FOUND",
  "REVISION_INTEGRITY_MISMATCH",
  "REVISION_NOT_ELIGIBLE",
  "VALIDATION_NOT_PASSED",
  "VALIDATION_REVISION_MISMATCH",
  "MIGRATION_PLAN_NOT_ELIGIBLE",
  "CHANGESET_NOT_FINALIZED",
  "REVISION_PARTIAL",
  "UNSUPPORTED_REVISION",
  "MAINNET_DEPLOYMENT_FORBIDDEN",
  "CHAIN_ID_MISMATCH",
  "UNKNOWN_DEPLOYMENT_TARGET",
  "DEPLOYMENT_TARGET_DISABLED",
  "REGISTRY_TARGET_MISMATCH",
  "TESTNET_FUNDING_UNAVAILABLE",
  "CANDIDATE_REQUIRED",
  "CANDIDATE_NOT_FOUND",
  "UNSUPPORTED_FRAMEWORK",
  "ARBITRARY_COMMAND_REJECTED",
  "ARBITRARY_RPC_REJECTED",
  "PREFLIGHT_FAILED",
  "POLICY_LIMIT_EXCEEDED",
  "CREDENTIAL_LOST",
  "BROADCAST_ALREADY_STARTED",
  "RECONCILIATION_REQUIRED",
  "SANDBOX_START_FAILED",
  "SANDBOX_POLICY_VIOLATION",
  "EXECUTION_TIMEOUT",
  "RPC_PROXY_FAILED",
  "CONFIRMATION_REQUIRED",
  "CONFIRMATION_MISMATCH",
  "DEPLOYMENT_NOT_FOUND",
  "DEPLOYMENT_NOT_ELIGIBLE",
  "DEPLOYMENT_FAILED",
] as const;

export type DeploymentErrorCode = (typeof DEPLOYMENT_ERROR_CODES)[number];

export const DEPLOYMENT_ERROR_MESSAGES: Record<DeploymentErrorCode, string> = {
  INVALID_REQUEST: "Request is invalid",
  REVISION_NOT_FOUND: "Repository revision not found",
  REVISION_INTEGRITY_MISMATCH: "Revision content hash did not match the persisted hash",
  REVISION_NOT_ELIGIBLE: "This revision is not eligible for testnet deployment",
  VALIDATION_NOT_PASSED: "Latest applicable validation did not pass",
  VALIDATION_REVISION_MISMATCH: "Validation run does not belong to this revision content hash",
  MIGRATION_PLAN_NOT_ELIGIBLE:
    "Migration plan still has blocked, unknown, manual, or unresolved review actions",
  CHANGESET_NOT_FINALIZED: "Safe changes exist but the ChangeSet is not finalized and complete",
  REVISION_PARTIAL: "Partial revisions cannot be deployed",
  UNSUPPORTED_REVISION: "Unsupported, failed, or unvalidated revisions cannot be deployed",
  MAINNET_DEPLOYMENT_FORBIDDEN: "Mainnet deployment is forbidden",
  CHAIN_ID_MISMATCH: "Target RPC chain ID does not match the registry",
  UNKNOWN_DEPLOYMENT_TARGET: "Deployment target is not in the ChainPort registry",
  DEPLOYMENT_TARGET_DISABLED: "Deployment is not enabled for this network",
  REGISTRY_TARGET_MISMATCH: "Requested target does not match the registry deployment target",
  TESTNET_FUNDING_UNAVAILABLE: "Testnet funding is unavailable",
  CANDIDATE_REQUIRED: "A deployment candidate must be selected",
  CANDIDATE_NOT_FOUND: "Deployment candidate was not found",
  UNSUPPORTED_FRAMEWORK: "This deployment framework is not supported by TESTNET_DEPLOY@1",
  ARBITRARY_COMMAND_REJECTED: "Arbitrary shell commands are not accepted",
  ARBITRARY_RPC_REJECTED: "Arbitrary RPC URLs are not accepted",
  PREFLIGHT_FAILED: "Deployment preflight/simulation failed",
  POLICY_LIMIT_EXCEEDED: "Deployment exceeded gas, value, or transaction policy limits",
  CREDENTIAL_LOST:
    "Disposable deployer credential is no longer available; prepare a new deployment",
  BROADCAST_ALREADY_STARTED: "Broadcast already started; the script will not be rerun",
  RECONCILIATION_REQUIRED: "Deployment state is uncertain and requires reconciliation",
  SANDBOX_START_FAILED: "The isolated deployment sandbox could not be started",
  SANDBOX_POLICY_VIOLATION: "Sandbox policy would have been violated",
  EXECUTION_TIMEOUT: "Deployment exceeded the configured timeout",
  RPC_PROXY_FAILED: "The ChainPort RPC proxy could not be started or verified",
  CONFIRMATION_REQUIRED: "Explicit confirmation to deploy to the named testnet is required",
  CONFIRMATION_MISMATCH: "Confirmation target does not match the prepared testnet",
  DEPLOYMENT_NOT_FOUND: "Deployment run not found",
  DEPLOYMENT_NOT_ELIGIBLE: "Deployment run is not in a state that allows this operation",
  DEPLOYMENT_FAILED: "Deployment failed",
};

export function isDeploymentErrorCode(value: unknown): value is DeploymentErrorCode {
  return typeof value === "string" && (DEPLOYMENT_ERROR_CODES as readonly string[]).includes(value);
}
